# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app

# Copy the project files and restore dependencies
COPY JobHunterApi/*.csproj ./
RUN dotnet restore

# Copy the rest of the app and publish it
COPY . ./
RUN dotnet publish -c Release -o out

# Use the official ASP.NET runtime image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app
EXPOSE 8080

# Copy the published app from the build image
COPY --from=build-env /app/out .

# Set environment variables (you can also set the connection string here)
ENV CONNECTION_STRING="Server=mysql;Database=JobHunter;User=root;Password=hitesh1312;Port=3306"

# Entry point to start the API
ENTRYPOINT ["dotnet", "JobHunterApi.dll"]
