
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: hitesh1312
      MYSQL_DATABASE: JobHunter
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=hitesh1312"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

jobhunter-api:
    build: .
    container_name: jobhunter-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=mysql;Database=JobHunter;User=root;Password=hitesh1312;Port=3306
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:



